import '../../features/product/domain/entities/product.dart';

final List<Product> sampleProducts = [
  Product(
    id: 'prod_1',
    name: 'Pedigree Vital Protection',
    category: 'Dog Food',
    description: 'Pedigree Vital Protection helps keep your dog healthy and full of vitality.',
    price: 1400,
    oldPrice: 1600,
    rating: 4.8,
    reviewCount: 230,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['1kg', '4kg', '8kg'],
    ratingSummary: RatingSummary(averageRating: 4.8, starPercentages: {5: 0.8, 4: 0.1, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_2',
    name: 'Royal Canin Maxi Adult',
    category: 'Dog Food',
    description: 'Balanced nutrition for large breed dogs from 15 months to 5 years.',
    price: 3200,
    oldPrice: 3500,
    rating: 4.9,
    reviewCount: 150,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['4kg', '15kg'],
    ratingSummary: RatingSummary(averageRating: 4.9, starPercentages: {5: 0.9, 4: 0.05, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_3',
    name: 'Pawtastic Dog Collar',
    category: 'Accessories',
    description: 'Durable and stylish nylon collar for your furry friend.',
    price: 650,
    oldPrice: 800,
    rating: 4.5,
    reviewCount: 85,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['S', 'M', 'L'],
    ratingSummary: RatingSummary(averageRating: 4.5, starPercentages: {5: 0.6, 4: 0.3, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_4',
    name: 'Plush Squeaky Toy',
    category: 'Toys',
    description: 'Soft and durable squeaky toy for dogs and cats.',
    price: 450,
    oldPrice: 600,
    rating: 4.7,
    reviewCount: 120,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['One Size'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.75, 4: 0.15, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_5',
    name: 'Cozy Pet Bed',
    category: 'Beds',
    description: 'Ultra-soft pet bed for a comfortable sleep.',
    price: 2500,
    oldPrice: 3000,
    rating: 4.6,
    reviewCount: 95,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['M', 'L', 'XL'],
    ratingSummary: RatingSummary(averageRating: 4.6, starPercentages: {5: 0.7, 4: 0.2, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_6',
    name: 'Meow Mix Cat Food',
    category: 'Cat Food',
    description: 'A delicious blend of chicken, turkey, salmon, and ocean fish.',
    price: 1200,
    oldPrice: 1400,
    rating: 4.4,
    reviewCount: 210,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['1.5kg', '3kg'],
    ratingSummary: RatingSummary(averageRating: 4.4, starPercentages: {5: 0.5, 4: 0.4, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_7',
    name: 'Cat Scratching Post',
    category: 'Toys',
    description: 'Heavy-duty scratching post with sisal rope.',
    price: 1800,
    oldPrice: 2200,
    rating: 4.7,
    reviewCount: 60,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['60cm', '80cm'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.8, 4: 0.1, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_8',
    name: 'Bird Seed Mix',
    category: 'Bird Food',
    description: 'Nutritious seed mix for all types of pet birds.',
    price: 350,
    oldPrice: 450,
    rating: 4.5,
    reviewCount: 45,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['500g', '1kg'],
    ratingSummary: RatingSummary(averageRating: 4.5, starPercentages: {5: 0.6, 4: 0.3, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_9',
    name: 'Rabbit Hutch',
    category: 'Cages',
    description: 'Spacious and secure outdoor hutch for rabbits.',
    price: 5500,
    oldPrice: 6500,
    rating: 4.3,
    reviewCount: 30,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['Large'],
    ratingSummary: RatingSummary(averageRating: 4.3, starPercentages: {5: 0.4, 4: 0.4, 3: 0.1, 2: 0.05, 1: 0.05}),
  ),
  Product(
    id: 'prod_10',
    name: 'Aquarium Starter Kit',
    category: 'Fish',
    description: 'Complete 20-gallon aquarium kit with filter and LED light.',
    price: 8500,
    oldPrice: 10000,
    rating: 4.8,
    reviewCount: 55,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['20 Gallon'],
    ratingSummary: RatingSummary(averageRating: 4.8, starPercentages: {5: 0.8, 4: 0.15, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_11',
    name: 'Flea and Tick Shampoo',
    category: 'Grooming',
    description: 'Effective shampoo to kill fleas and ticks on contact.',
    price: 750,
    oldPrice: 900,
    rating: 4.5,
    reviewCount: 110,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['250ml', '500ml'],
    ratingSummary: RatingSummary(averageRating: 4.5, starPercentages: {5: 0.6, 4: 0.3, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_12',
    name: 'Reflective Pet Leash',
    category: 'Accessories',
    description: 'High-visibility leash for safe nighttime walks.',
    price: 550,
    oldPrice: 700,
    rating: 4.6,
    reviewCount: 70,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['1.5m', '2m'],
    ratingSummary: RatingSummary(averageRating: 4.6, starPercentages: {5: 0.7, 4: 0.2, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_13',
    name: 'Hammock for Cats',
    category: 'Beds',
    description: 'Window-mounted hammock for cats to enjoy the view.',
    price: 1500,
    oldPrice: 1800,
    rating: 4.7,
    reviewCount: 40,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['Standard'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.8, 4: 0.15, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_14',
    name: 'Hamster Ball',
    category: 'Toys',
    description: 'Fun and safe exercise ball for hamsters.',
    price: 300,
    oldPrice: 400,
    rating: 4.2,
    reviewCount: 50,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['Small', 'Large'],
    ratingSummary: RatingSummary(averageRating: 4.2, starPercentages: {5: 0.4, 4: 0.4, 3: 0.1, 2: 0.05, 1: 0.05}),
  ),
  Product(
    id: 'prod_15',
    name: 'Stainless Steel Pet Bowl',
    category: 'Accessories',
    description: 'Durable and easy to clean stainless steel bowl.',
    price: 400,
    oldPrice: 500,
    rating: 4.9,
    reviewCount: 300,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['S', 'M', 'L'],
    ratingSummary: RatingSummary(averageRating: 4.9, starPercentages: {5: 0.9, 4: 0.08, 3: 0.01, 2: 0.01, 0: 0.0}),
  ),
  Product(
    id: 'prod_16',
    name: 'Catnip Filled Mouse',
    category: 'Toys',
    description: 'Classic toy filled with premium North American catnip.',
    price: 250,
    oldPrice: 350,
    rating: 4.8,
    reviewCount: 180,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['One Size'],
    ratingSummary: RatingSummary(averageRating: 4.8, starPercentages: {5: 0.85, 4: 0.1, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_17',
    name: 'Adjustable Pet Harness',
    category: 'Accessories',
    description: 'Comfortable and secure harness with adjustable straps.',
    price: 950,
    oldPrice: 1200,
    rating: 4.7,
    reviewCount: 90,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['XS', 'S', 'M', 'L'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.75, 4: 0.2, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_18',
    name: 'Dental Chews for Dogs',
    category: 'Health',
    description: 'Helps clean teeth and freshen breath.',
    price: 850,
    oldPrice: 1000,
    rating: 4.6,
    reviewCount: 140,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['10 Pack', '30 Pack'],
    ratingSummary: RatingSummary(averageRating: 4.6, starPercentages: {5: 0.65, 4: 0.25, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_19',
    name: 'Reptile Heat Lamp',
    category: 'Health',
    description: 'Provides essential UVA and UVB rays for reptiles.',
    price: 1200,
    oldPrice: 1500,
    rating: 4.4,
    reviewCount: 35,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['50W', '100W'],
    ratingSummary: RatingSummary(averageRating: 4.4, starPercentages: {5: 0.5, 4: 0.4, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_20',
    name: 'Pet Hair Remover Brush',
    category: 'Grooming',
    description: 'Easily remove pet hair from clothes and furniture.',
    price: 350,
    oldPrice: 500,
    rating: 4.3,
    reviewCount: 250,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['One Size'],
    ratingSummary: RatingSummary(averageRating: 4.3, starPercentages: {5: 0.45, 4: 0.4, 3: 0.1, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_21',
    name: 'Salmon Oil for Pets',
    category: 'Health',
    description: 'Supports healthy skin, coat, and joint health.',
    price: 1600,
    oldPrice: 2000,
    rating: 4.8,
    reviewCount: 75,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['250ml', '500ml'],
    ratingSummary: RatingSummary(averageRating: 4.8, starPercentages: {5: 0.8, 4: 0.15, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_22',
    name: 'Automatic Pet Feeder',
    category: 'Accessories',
    description: 'Programmable feeder for scheduled meal times.',
    price: 4500,
    oldPrice: 5500,
    rating: 4.7,
    reviewCount: 45,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['4L', '6L'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.75, 4: 0.2, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
  Product(
    id: 'prod_23',
    name: 'Guinea Pig Tunnel',
    category: 'Toys',
    description: 'Collapsible tunnel for guinea pigs and other small pets.',
    price: 600,
    oldPrice: 800,
    rating: 4.5,
    reviewCount: 65,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['Small'],
    ratingSummary: RatingSummary(averageRating: 4.5, starPercentages: {5: 0.6, 4: 0.3, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_24',
    name: 'Parrot Training Stand',
    category: 'Toys',
    description: 'Portable tabletop stand for bird training.',
    price: 2200,
    oldPrice: 2800,
    rating: 4.6,
    reviewCount: 25,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['Standard'],
    ratingSummary: RatingSummary(averageRating: 4.6, starPercentages: {5: 0.7, 4: 0.2, 3: 0.05, 2: 0.03, 1: 0.02}),
  ),
  Product(
    id: 'prod_25',
    name: 'Slow Feeder Bowl',
    category: 'Accessories',
    description: 'Prevents rapid eating and promotes healthy digestion.',
    price: 500,
    oldPrice: 700,
    rating: 4.7,
    reviewCount: 130,
    images: ['assets/images/dashboard_assets/sample_product.png'],
    sizes: ['S', 'M', 'L'],
    ratingSummary: RatingSummary(averageRating: 4.7, starPercentages: {5: 0.75, 4: 0.2, 3: 0.03, 2: 0.01, 1: 0.01}),
  ),
];
