// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKrhiWSeFL-VtORE3et1hEvGF-1PdaR8',
    appId: '1:923851122658:android:bfdffca23e2128c635bbbb',
    messagingSenderId: '923851122658',
    projectId: 'divinepets-5e73e',
    storageBucket: 'divinepets-5e73e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ordsYBIIpk6okGx5woA6f4xvwA_IRic',
    appId: '1:923851122658:ios:e0eac69f8757150c35bbbb',
    messagingSenderId: '923851122658',
    projectId: 'divinepets-5e73e',
    storageBucket: 'divinepets-5e73e.firebasestorage.app',
    iosBundleId: 'com.codeinfinity.divinepets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFEXVDjNWFx-tl2vKtWWDzbMeoGAO5v4A',
    appId: '1:923851122658:web:6f7ada986c6b4dd035bbbb',
    messagingSenderId: '923851122658',
    projectId: 'divinepets-5e73e',
    authDomain: 'divinepets-5e73e.firebaseapp.com',
    storageBucket: 'divinepets-5e73e.firebasestorage.app',
  );
}
